"""updated feedback model!

Revision ID: da60bb081615
Revises: 39f7e5b0fe9f
Create Date: 2026-09-03 20:16:30.787670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da60bb081615'
down_revision: Union[str, None] = '39f7e5b0fe9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_feedback', sa.Column('id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'client_feedback', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_feedback', type_='unique')
    op.drop_column('client_feedback', 'id')
    # ### end Alembic commands ###
